### ISSUE TITLE
Not working because of API Changes

### ISSUE THREAD

**Issue by deepak-arora** [blockchain/api-v1-client-csharp#10]
My project is created using 'api-v1-client-csharp' and now as per bitcoin I need to setup bitcoin wallet server locally. I have done this setup locally but from where to get update api dll to use with new api that connects me via local blockchain server.

**Comment by mpfluger** [comment]
We will release an updated version of the API libraries shortly with an option to pass in the URL of the local service-my-wallet service. Thanks for your feedback.

**Comment by deepak-arora** [comment]
Thanks for your response mpfluger.

Could you please let me know, when I can expect the release as I have implemented it on one of my client application now I need to answer him.?

Will it support multiple wallet login at a time.?? 

as per api v3 doc I found ref: (https://github.com/blockchain/service-my-wallet-v3)
Note: at the moment, only one wallet can be "logged into" at a time. To make api calls to different wallets, run separate instances of this service for each wallet, or just remember to call /login each time you want to switch wallets.

My application checks multiple wallet, If wallet api v3 will support one login at a time only, how can I handle this situation.?

Sorry for so many question but I am worried as it's implemented in one of my client's running system.

**Comment by mpfluger** [comment]
We will update all API libraries in the coming days, starting with C# to get you set up and running asap.

The latest version of service-my-wallet-v3 (0.17.2) now supports being logged into multiple wallets at the same time. We will update the docs shortly.

**Comment by mpfluger** [comment]
Sorry for the delay, we are still working on updating all the libraries. We will release new versions next week.

**Comment by mpfluger** [comment]
It's fixed now in release v2.0.0 and published to Nuget.

**Comment by deepak-arora** [comment]
Hi Mark. 

I have updated the solution with latest release v2.0.0. Now how can I update my C# code with new release. I noticed a significant changes in class libraries so I need to update my source code as per new C# v2.0.0 library. Can you please provide you provide C# API library sample source code or document..??

**Comment by alecalve** [comment]
I updated the code example [here](https://github.com/blockchain/api-v1-client-csharp/blob/master/docs/wallet.md).

**Comment by hitjariwala** [comment]
Hi,

can you tell me where find API code and serviceUrl
