### ISSUE TITLE
Totally not working 

### ISSUE THREAD

**Issue by NoRoomInHell** [blockchain/api-v1-client-csharp#12]
Just trying to get some information from Statistics, there is no method like Get() or something else, only StatisticsResponse and StatisticsExplorer and these classes have no construction defined. What am i doing wrong?

**Comment by alecalve** [comment]
Hi, I would suggest you to try this code:

```csharp
using (BlockchainApiHelper apiHelper = new BlockchainApiHelper())
{
    StatisticsResponse response = await apiHelper.StatisticsExplorer.GetAsync();
    Console.WriteLine(response.MarketPriceUsd);
    ...
}
```

**Comment by NoRoomInHell** [comment]
Thanks for reply, i manipulated with your code, so it working for me now

`static  void Main(string[] args)        
        {
            var method = SomeDouble();
            double result = method.Result;
            Console.WriteLine(result);
        }
        static async Task<double> SomeDouble()
        {
            using (Info.Blockchain.API.BlockchainApiHelper pp = new BlockchainApiHelper())
            {
                Info.Blockchain.API.Statistics.StatisticsResponse resp = await   pp.StatisticsExplorer.GetAsync();
                return resp.MarketPriceUsd;    
            }            
        }`
