### ISSUE TITLE
How can i get last transaction?

### ISSUE THREAD

**Issue by NoRoomInHell** [blockchain/api-v1-client-csharp#13]
Could i get (for example) lates 10 transactions from main page blockchain.info?

**Comment by jtormey** [comment]
The BlockExplorer class has a method [GetUnconfirmedTransactionsAsync](https://github.com/blockchain/api-v1-client-csharp/blob/master/src/Info.Blockchain.API/BlockExplorer/BlockExplorer.cs#L243). This will fetch a list of all the latest transactions for you.

**Comment by NoRoomInHell** [comment]
Thanks for answer,problem was solved !

**Comment by jtormey** [comment]
Great to hear!
