### ISSUE TITLE
BlockExplorer constructor doesnt work

### ISSUE THREAD

**Issue by bitcoinbrisbane** [blockchain/api-v1-client-csharp#19]
This line doest work 

var blockExplorer = new BlockExplorer();

I get the error, They type... has no constructor defined.

**Comment by boomtnt46** [comment]
It doesn't work to me too!!! Please fix!!!

**Comment by assafY** [comment]
This client has recently been migrated to .NET Core, and the docs were updated accordingly - everything should be working fine now.
