### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by nstuller** [blockchain/api-v1-client-csharp#2]
When I make a call to Statistics.Get(), it works the first time. However, when I call it again later in my application, I get the error: The request was aborted: Could not create SSL/TLS secure channel.

I saw online a way to resolve this by including ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 in my code, but this seems like something that should be resolved in the library.

**Comment by solidcloudio** [comment]
I'm having this issue as well..  But when I try to create multiple wallets with the same wallet context
