### ISSUE TITLE
.NET Core Portage

### ISSUE THREAD

**Issue by MaherJendoubi** [blockchain/api-v1-client-csharp#21]
Hello,

I forked this project and I tried to port it to .NET Core. Please have a look https://github.com/MaherJendoubi/Info.Blockchain.API

Sorry to write it here as an issue, but it's rather a suggestion: Is it possible to create a new project api-v1-client-NETCore?
Best,
Maher

**Comment by robertsundstrom** [comment]
Cool, @MaherJendoubi.

Maybe you should submit it as a pull request? That might give some attention.

**Comment by ArturKarbone** [comment]
@MaherJendoubi  any news on this? a lot has changed in .NET Core. Need some help?

**Comment by assafY** [comment]
This client was recently migrated to .NET Core and the docs were updated accordingly.
