### ISSUE TITLE
Documentations seem to be out of date!

### ISSUE THREAD

**Issue by alirezanoori1986** [blockchain/api-v1-client-csharp#22]
Hi!

I installed your library using the Nuget package and I'm trying to use your C# API. Unfortunately it seems like none of the code samples provided here work.

For instance I wanted to get the ticker. Using the following code: `ExchangeRates.GetTicker();`
However, I get an error saying that `The type or namespace name 'GetTicker' does not exist in the namespace 'Info.Blockchain.API.ExchangeRates'`.

Also I couldn't create a wallet using the sample provide in [this link](https://github.com/blockchain/api-v1-client-csharp/blob/master/docs/createwallet.md)

If possible, please provide me a little sample on how to:

- Create a new wallet
- Transfer bitcoins from one address to another
- Get the latest exchange rates

Any document/video/article would be greatly appreciated. Thanks in advance.

**Comment by csancho** [comment]
Totally agree. I join the request for updated documentation and examples to create Wallets and make transfers. Is it mandatory to create a local application on Node to create Wallets?
Thanks

**Comment by bitcoinbrisbane** [comment]
Seems like this project has been abandoned.  Lots of errors, out of date doco.  Explorer constructor doesnt work.

**Comment by assafY** [comment]
This client has recently been upgraded and the docs were updated. The issue you raised should now be fixed.

**Comment by GaikwadPratik** [comment]
@assafY,

Can you please update the documentation to include sample codes for usage of api. The current documentation is very inadequate and vague making it difficult to understand. Any help would be greatly appreciated!

**Comment by assafY** [comment]
@GaikwadPratik do you find the usage examples at the bottom of every doc unhelpful? Is there an area in particular that you find vague?

I will take a look at the docs when I can but for the time being if there is any particular issue you are having, let me know.
