### ISSUE TITLE
Error in : Install-Package BlockchainAPI

### ISSUE THREAD

**Issue by umraodhananjay** [blockchain/api-v1-client-csharp#27]
PM> Install-Package BlockchainAPI
Install-Package : An error occurred while loading packages from'https://nuget.org/api/v2/': The underlying connection was closed: An unexp
ected error occurred on a send.
At line:1 char:16
+ Install-Package <<<<  BlockchainAPI
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by umraodhananjay** [comment]
Please give me solution of this error

:+1: 
PM> Install-Package BlockchainAPI
Install-Package : An error occurred while loading packages from'https://nuget.org/api/v2/': The underlying connection was closed: An unexp
ected error occurred on a send.
At line:1 char:16
+ Install-Package <<<<  BlockchainAPI
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by assafY** [comment]
This error does not seem to be specific to the Blockchain api client. Can you look at the solutions here 

https://nuget.codeplex.com/discussions/275537

and let me know if that solved the issue?
