### ISSUE TITLE
API method to generate xpub keys

### ISSUE THREAD

**Issue by carl-wha** [blockchain/api-v1-client-csharp#28]
I'm going through the API and there seems to be no API call to generate xpub keys.
Is there a way to do this?

**Comment by assafY** [comment]
What do you mean by generating xpub keys? The API allows you to generate new receive addresses for an existing xpub key.

https://github.com/blockchain/api-v1-client-csharp/blob/master/docs/receive.md

However, you need to obtain xpub and api keys to use this functionality. Look at the link below for more information.

https://blockchain.info/api/api_receive
