### ISSUE TITLE
.net 4.6 library

### ISSUE THREAD

**Issue by Marjani** [blockchain/api-v1-client-csharp#30]
Hi
I'm using Visual Studio 2015 and .NET Framework 4.6
Where can I find the right library for  4.6?

**Comment by assafY** [comment]
Hi,

As this client was upgraded to `csproj` format rather than `project.json`, it does not support Visual Studio 2015 - you would have to use Visual Studio 2017 to import this project.

Referencing .NET 4.6 is just a matter of opening the `csproj` file and changing
```
<PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
</PropertyGroup>
```
to
```
<PropertyGroup>
    <TargetFramework>net46</TargetFramework>
</PropertyGroup>
```
