### ISSUE TITLE
Blockchain exception

### ISSUE THREAD

**Issue by ghost** [blockchain/api-v1-client-csharp#32]
Hello, 
My problem is that I cannot interact with the api in combination with the service-my-wallet-v3. I have installed this service on my debian 8 machine and the link manually is working also if i try it with parameters for the single functions. If i put this link into the BlockchainApiHelper 
using (BlockchainApiHelper apiHelper = new BlockchainApiHelper(apiCode: "", service_url: "http:127.0.0.1:3000")) i get since 2 days the error that this is a wrong service_url. The 127.0.0.1 adress is only to show there stands my rootserver ip. I also had put this ip by blockchain as whitelist that i dont must do the email confirmation. 
The Exception from the Programm gives me this back: 
Blockchain exception: In order to create wallets, you must provide a valid service_url to BlockchainApiHelper. 

I am using your example which you gave: https://github.com/blockchain/api-v1-client-csharp/blob/master/docs/wallet.md. I have removed the sending of btc to a adress. And also changed the apikey to my key and its still not working. 

Pls help me with this issue. I dont now what i can do more now.

**Comment by assafY** [comment]
Hi,

Can you try creating a wallet without using the `BlockchainApiHelper`?

You can try:

```
var httpClient = new BlockchainHttpClient("api-code", "http://127.0.0.1:3000");
var walletCreator = new WalletCreator(httpClient);
walletCreator.CreateAsync("some-password")
```
