### ISSUE TITLE
Receive Api Error

### ISSUE THREAD

**Issue by proBeejay141** [blockchain/api-v1-client-csharp#35]
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Not Found: {"error":"Not found"}
Info.Blockchain.API.Client.ServerApiException: Not Found: {"error":"Not found"}

**Comment by denis32000** [comment]
the same problem. @proBeejay141 how did you handle this?

**Comment by assafY** [comment]
https://github.com/blockchain/api-v1-client-csharp/issues/37
