### ISSUE TITLE
Anyone here?

### ISSUE THREAD

**Issue by lepipele** [blockchain/api-v1-client-csharp#4]
Is anyone from Blockchain team monitoring these issues?

I am looking to submit few pull requests to improve usage of the library - let me know if you will be available to review the requests.

**Comment by tuzzolo** [comment]
Yes we're here.

**Comment by lepipele** [comment]
OK, I'll make some changes so that project is easier to use with Nuget Automatic Package Restore:
https://docs.nuget.org/consume/package-restore

Will send pull request once I prepare it. One question - are you open to modifying structure of project to move source to src folder? This way you have .cs files in root, docs folder is mixed with other source folders - not really best approach. Let me know and I can introduce this change also.

Thanks!

**Comment by tuzzolo** [comment]
Ok great.

I'm open to structure being modifying / organized a bit to keep source and docs a bit more separate.

**Comment by lepipele** [comment]
OK, perfect - I already have a project on which I plan to use the library so I'll run all tests, make sure it's easy to integrate and then create pull request.

**Comment by hitjariwala** [comment]
When i run it see error. can any help me?

In order to create wallets, you must provide a valid service_url to BlockchainApiHelper
