### ISSUE TITLE
Confirmations?

### ISSUE THREAD

**Issue by solidcloudio** [blockchain/api-v1-client-csharp#6]
How can I get the number of confirmations for a transaction?

**Comment by rfiori** [comment]
You can using this bnitnet.dll  http://sourceforge.net/projects/bitnet/
Will return a JObject similar in Blockchain API https://blockchain.info/api/json_rpc_api 
Method: gettransaction

**Comment by rfiori** [comment]
See this, is better way.
http://stackoverflow.com/questions/14989481/blockchain-api-to-determine-transaction-confirmations

**Comment by KMHouk** [comment]
Thanks @rfiori for the assistance here. That is currently the best way to look up confirmations for a transaction, we'll see if we can update this library to include a more seamless way to look up the number of confirmations for a given transaction.

Best,
Kevin
