### ISSUE TITLE
Issue with wallet getBalance C#

### ISSUE THREAD

**Issue by deepak-arora** [blockchain/api-v1-client-csharp#9]
I am using this api since one year I haven't changed my code but now when I call wallet.getBalance() function it shows me exception.

Unexpected character encountered while parsing value: <. Path '', line 4, position 1.

I have not checked other wallet functions but it seems like all wallet related api not working now.

**Comment by 5877** [comment]
[python-client.zip](https://github.com/blockchain/api-v1-client-csharp/files/147410/python-client.zip)

**Comment by deepak-arora** [comment]
I have my existing code created in c# and can't move to python to upgrade this. I need it to upgrade in c# only. please suggest.

**Comment by alecalve** [comment]
In order to use wallet calls like getBalance you must now use [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3). This client has been updated to interface with it.

**Comment by deepak-arora** [comment]
But this api not supported with multiple wallet login. Moreover I am using blockchain api-v1-client-csharp. Now I am not sure how to use service  v3 in C#, because no v3 csharp code is released yet. Please help.

**Comment by alecalve** [comment]
It updated the code example [here](https://github.com/blockchain/api-v1-client-csharp/blob/master/docs/wallet.md).

**Comment by deepak-arora** [comment]
The code you provided is not working for me. I need to access multiple wallet. Even it's now getting balance for single wallet.

**Comment by alecalve** [comment]
A `WalletHelper` only works for one wallet. In order to access the balances of several wallets, you need to create one `WalletHelper` per wallet.

**Comment by deepak-arora** [comment]
working fine for first wallet, but after then i am calling wallet helper for another wallet, its through exception. please see my attached screen and code below.
![error_bitcoin](https://cloud.githubusercontent.com/assets/2249781/15541192/ec5e1902-22a8-11e6-9a0c-3671a2c0f97d.png)

`using (BlockchainApiHelper apiHelper = new BlockchainApiHelper(apiCode: "APIKEY1", serviceUrl: "http://192.168.0.118:3000"))
            {
                try
                {
                    WalletHelper helper = apiHelper.CreateWalletHelper("WalletId1", "Password");                  
                    Info.Blockchain.API.Wallet.Address addr = await helper.GetAddressAsync("Address1", 3);
                    Console.WriteLine("The balance is {0}", addr.Balance);                   
                }
                catch (Exception ex)
                {
                }
            }
                 
            using (BlockchainApiHelper apiHelper = new BlockchainApiHelper(apiCode: "APIKEY2", serviceUrl: "http://192.168.0.118:3000"))
            {
                try
                {
                    WalletHelper helper = apiHelper.CreateWalletHelper("WalletId2", "Password");                    
                    Info.Blockchain.API.Wallet.Address addr = await helper.GetAddressAsync("Address2", 3);
                    Console.WriteLine("The balance is {0}", addr.Balance);                    
                    Console.Read();
                }
                catch (Exception ex)
                {
                }`

**Comment by alecalve** [comment]
The error in your screenshot is:  `Address not found in this wallet`. Are you sure `Address2` belongs to `WalletId2` in your code?

**Comment by deepak-arora** [comment]
I am sure that Address2 is right.

**Comment by alecalve** [comment]
What version of [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3) are you running?

**Comment by deepak-arora** [comment]
https://github.com/blockchain/api-v1-client-csharp

**Comment by alecalve** [comment]
No, I mean what version of the wallet service is running on `http://192.168.0.118:3000`?

**Comment by deepak-arora** [comment]
I am using code from this link
https://github.com/blockchain/api-v1-client-csharp/blob/master/docs/wallet.md
And version of the wallet service is V2.

**Comment by alecalve** [comment]
Thanks for the information. Is `Address2` in the data returned by calling `http://192.168.0.118:3000/merchant/<your guid>/list?api_code=<your api code>&password=<your password>` with the second wallet's data?

**Comment by deepak-arora** [comment]
YES, `Address2` is the data in to my second wallet data.
Please see the attached screen of my addresses in to my second wallet...

![capture](https://cloud.githubusercontent.com/assets/2249781/15571637/938a4cfe-2359-11e6-988c-f6c68daeabe5.PNG)

**Comment by alecalve** [comment]
Does the password for the second wallet contains any special characters (like punctuation, percent signs, etc..)?

**Comment by deepak-arora** [comment]
No, I am not using any special characters (like punctuation, percent signs, etc..), My password is just string and number like -  Developer12345 .

**Comment by alecalve** [comment]
Is the password for the second wallet correct? I noticed that the error message for calls to `GetAddressAsync` with a wrong password is the one you have. You can check if the password is correct by adding:

```csharp
List<Address> addresses = await helper.ListAddressesAsync();
Console.WriteLine("Addresses listed: {0}", addresses.Count);
```

right before the call to `GetAddressAsync`. If the password is not correct, the exception will be `Main wallet password incorrect`

**Comment by deepak-arora** [comment]
the password for the second wallet is absolutely correct.
